#!/bin/bash
#SBATCH -J myjob
#SBATCH -o myjob.o%j
#SBATCH -e myjob.e%j
#SBATCH -N 1 # This line should not be changed.
#SBATCH -n 56 # Number of MPI tasks should be controlled here.
#SBATCH -t 00:20:00 # Run time (hh:mm:ss)
#SBATCH -A EPW-SCHOOL # This line should not be changed.
#SBATCH -p small # This line should not be changed.
#SBATCH --reservation=EPW-SCHOOL-06-17-2021 # Dates should be updated during the school.

module purge
module load TACC

export QEF='/work2/06868/giustino/EPW-SCHOOL/q-e/bin'

